import {
  blue,
  crimson,
  cyan,
  grass,
  gray,
  green,
  indigo,
  iris,
  jade,
  pink,
  plum,
  purple,
  red,
  ruby,
  teal,
  tomato,
  violet,
} from "@radix-ui/colors";

export const colors = {
  accent: blue.blue9,
  contrast: {
    light: gray.gray12,
    dark: gray.gray1,
  },
  light: {
    tomato: tomato.tomato9,
    red: red.red9,
    ruby: ruby.ruby9,
    crimson: crimson.crimson9,
    pink: pink.pink9,
    plum: plum.plum9,
    purple: purple.purple9,
    violet: violet.violet9,
    iris: iris.iris9,
    indigo: indigo.indigo9,
    blue: blue.blue9,
    cyan: cyan.cyan9,
    teal: teal.teal9,
    jade: jade.jade9,
    green: green.green9,
    grass: grass.grass9,
    gray: gray.gray9,
  },
  dark: {
    tomato: tomato.tomato12,
    red: red.red12,
    ruby: ruby.ruby12,
    crimson: crimson.crimson12,
    pink: pink.pink12,
    plum: plum.plum12,
    purple: purple.purple12,
    violet: violet.violet12,
    iris: iris.iris12,
    indigo: indigo.indigo12,
    blue: blue.blue12,
    cyan: cyan.cyan12,
    teal: teal.teal12,
    jade: jade.jade12,
    green: green.green12,
    grass: grass.grass12,
    gray: gray.gray12,
  },
};
